---
title: "Map_NFDP"
author: "Chen-Chia Ku"
date: "2024-12-19"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
setwd("D:/Drive/2_lab/Pro0_NanjenshanData/10S_南仁山資料/Map_NanjenshanFDP/NFDP_Map")
```

```{r}
library(ggplot2)
library(dplyr)
library(metR)
```

```{r}
Lan <- read.csv("./Data/LanEnv.csv")

```

```{r}

Lan1 <- Lan %>%
  mutate(x=(X1-26)*10, 
         y=(Y1-17)*10)

ggplot()+
  geom_contour(Lan1, mapping=aes(x=x, y=y, z=Elevation), bins =15, , col="gray60")+
  geom_text_contour(data=Lan1 , mapping=aes(x=x, y=y, z=Elevation), 
                    stroke = 0.2, size=3,
                    breaks = seq(250, 340, by =5),
                    col="grey40", stroke.color="#C6E0BE")+
  scale_x_continuous(expand = c(0, 0), breaks=seq(0, 290, by=10),labels = seq(0, 290, by=10))+
  scale_y_continuous(expand = c(0, 0), breaks=seq(0, 210, by=10),labels = seq(0, 210, by=10))+
  geom_rect(aes(xmin = 240, xmax =290, ymin = 0, ymax = 120), fill="white", color="black", linewidth=1.5)+
  theme(axis.line.x=element_line(colour = "black", size=0.7),
        axis.line.y=element_line(colour = "black", size=0.7),
        axis.ticks.x=element_line(colour = "black", size=0.3),
        axis.ticks.y=element_line(colour = "black", size=0.3),
        axis.ticks.length=unit(0.1, "cm"),
        #panel.grid.major = element_line(colour = "yellow"),
        legend.title=element_text(size=10),
        text=element_text(size=14),
        plot.title = element_text(size=rel(1.5),hjust = -0.05),
        panel.border = element_rect(colour = "black", fill=NA, size=2),
        legend.position = "none",
        panel.background = element_rect(fill = "white"))+
  xlab('Distance (m)')+
  ylab("Distance (m)")
  

```

